In [3]:
import tensorflow as tf

In [2]:
!pip install tensorflow

  Using cached tensorflow-2.9.1-cp38-cp38-win_amd64.whl (444.1 MB)
     ---------------------------------------- 14.2/14.2 MB 3.7 MB/s eta 0:00:00
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached tensorboard-2.9.1-py3-none-any.whl (5.8 MB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     -------------------------------------- 123.4/123.4 kB 3.6 MB/s eta 0:00:00
  Using cached keras-2.9.0-py2.py3-none-any.whl (1.6 MB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached termcolor-1.1.0-py3-none-any.whl
  Using cached tensorflow_estimator-2.9.0-py2.py3-none-any.whl (438 kB)
  Using cached tensorflow_io_gcs_filesystem-0.26.0-cp38-cp38-win_amd64.whl (1.5 MB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
     -------------------------------------- 895.9/895.9 kB 5.7 MB/s eta 0:00:00
     --------

In [4]:
import numpy as np

In [5]:
# Rank 0 Tensor (Scaler)
a = tf.constant(3)
print(a) # 'a' is a Rank 0 Tensor (0 dimensional array) of Int32

tf.Tensor(3, shape=(), dtype=int32)


In [6]:
b = tf.constant([1,2,3,4])
b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [7]:
c = tf.constant([[1,2],[3,4]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

## Converting a numpy array to tensor

In [8]:
array = np.array([1 , 2 , 3 , 4])
print(" Before " , array)
array = tf.convert_to_tensor(array)
print(" After " , array)

 Before  [1 2 3 4]
 After  tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


## Arthematic operations on Tensor

In [9]:
tensor = tf.constant([[1 , 2] , [3 , 4]])

In [10]:
tensor = tf.add(tensor,1)
print('Added 1',tensor)

Added 1 tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [11]:
#sub
tensor = tf.subtract(tensor,1)
print('Subtracted 1',tensor)

Subtracted 1 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [12]:
#multiplication
tensor = tf.matmul(tensor , tensor)
print(" Multiply " , tensor)

 Multiply  tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
